# Generated by Django 3.2 on 2021-04-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepie',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
